[[language]]
name = "zig"
roots = ["build.zig", "build.zig.zon"]
file-types = ["zig", "zon"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "yaml"
auto-format = false
formatter = { command = "yamlfmt", args = ["-"] }
