[language-server.zls.config]
"zig.zls.includeAtInBuiltins" = true
"zig.zls.enableSnippets" = false

[[language]]
name = "zig"
roots = ["build.zig", "build.zig.zon"]
file-types = ["zig", "zon"]
indent = { tab-width = 4, unit = "    " }
