[language-server.zls.config]
"zig.zls.enableSemanticTokens" = true
"zig.zls.enableInlayHints" = true
"zig.zls.inlayHintsShowBuiltin" = false
"zig.zls.inlayHintsExcludeSingleArgument" = true
"zig.zls.inlayHintsHideRedundantParamNames" = true
"zig.zls.inlayHintsHideRedundantParamNamesLastToken" = true
"zig.zls.warnStyle" = true
"zig.zls.highlightGlobalVarDeclarations" = true
"zig.zls.includeAtInBuiltins" = true

[[language]]
name = "zig"
roots = ["build.zig", "build.zig.zon"]
file-types = ["zig", "zon"]
indent = { tab-width = 4, unit = "    " }
